apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: webshare-api
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: openstaticfish-microservices
  config: dev
  managedSecret:
    name: webshare-api
    namespace: default
    type: Opaque
  secrets:
    - WEBSHARE_API_KEY
    - WEBSHARE_PROXY_USERNAME
    - WEBSHARE_PROXY_PASSWORD
  processors:
    WEBSHARE_API_KEY:
      type: plain
      asName: api-key
    WEBSHARE_PROXY_USERNAME:
      type: plain
      asName: proxy-username
    WEBSHARE_PROXY_PASSWORD:
      type: plain
      asName: proxy-password
