apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - webshare-api-externalsecret.yaml
  - site-analyzer-deployment.yaml
  - site-analyzer-service.yaml
  - site-analyzer-servicemonitor.yaml
  - site-analyzer-hpa.yaml
  - lightpanda-cdp-deployment.yaml
  - lightpanda-cdp-service.yaml
  - lightpanda-cdp-hpa.yaml
  - lightpanda-mcp-deployment.yaml
  - lightpanda-mcp-service.yaml
  - lightpanda-mcp-hpa.yaml
  - scraper-deployment.yaml
  - scraper-service.yaml
  - scraper-servicemonitor.yaml
  - scraper-hpa.yaml
  - microservices-workload-prometheusrule.yaml
  - microservices-http-prometheusrule.yaml
  - traefik-middleware-strip-prefix.yaml
  - ingressroute-microservices.yaml
images:
  - name: ghcr.io/openstaticfish/microservices/site-analyzer
    newTag: 15b47df1f5ad7a27cd68453faf2cd68267d6ceb2
  - name: ghcr.io/openstaticfish/microservices/scraper
    newTag: 15b47df1f5ad7a27cd68453faf2cd68267d6ceb2
  - name: ghcr.io/openstaticfish/microservices/lightpanda-mcp
    newTag: 15b47df1f5ad7a27cd68453faf2cd68267d6ceb2
