apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webshare-api
  namespace: microservices
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-openstaticfish-microservices
    kind: ClusterSecretStore
  target:
    name: webshare-api
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        api-key: "{{ .webshareApiKey }}"
        proxy-username: "{{ .webshareProxyUsername }}"
        proxy-password: "{{ .webshareProxyPassword }}"
  data:
    - secretKey: webshareApiKey
      remoteRef:
        key: WEBSHARE_API_KEY
    - secretKey: webshareProxyUsername
      remoteRef:
        key: WEBSHARE_PROXY_USERNAME
    - secretKey: webshareProxyPassword
      remoteRef:
        key: WEBSHARE_PROXY_PASSWORD
